### ISSUE TITLE
Scss

### ISSUE THREAD

**Issue by ArpitamSaha** [ArpitamSaha/Portfolio#1]
Need a bit of help in scss

**Comment by binay-tripathy** [comment]
Hey!! I would like to help you in scss. What kind of help do you need?

**Comment by ArpitamSaha** [comment]
I have done the css, I want to modify it to scss, I need some regarding the same

**Comment by binay-tripathy** [comment]
Ok I got you! Would gladly help you with that.

**Comment by ArpitamSaha** [comment]
Thanks for the help Binay, really appreciated
